### ISSUE TITLE
Finish setting up Rubocop

### ISSUE THREAD

**Issue by farleyknight** [kasiaekiert/doctor#14]
I believe we added the Rubocop gem? The goal with this task is to look at the list of Rubocop complaints and decide which ones actually matter and which ones are not our problem. I want you to put this file in your project as `.rubocop.yml`:

```yaml
Style/Documentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false
```

If you add this file, then `rubocop` will run clean in the terminal:

```shell
$ rubocop
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
.rubocop.yml:1: `Style/Documentation` is concealed by line 4
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Style/HashEachMethods (0.80)
 - Style/HashTransformKeys (0.80)
 - Style/HashTransformValues (0.80)
For more information: https://docs.rubocop.org/en/latest/versioning/
Inspecting 65 files
.................................................................

65 files inspected, no offenses detected
```

The goal of this exercise is to enable some of these configurations and decide if it would be difficult to fix. And if it won't be difficult to fix, then fix it immediately. For example, try changing the `Enabled:` flag on this part of the configuration from `false` to `true`:

```yaml
Style/StringLiterals:
  Enabled: true # Change this value
```

Now re-run `rubocop`:

```shell
Offenses:

db/migrate/20200310124832_devise_create_authors.rb:7:59: C: Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
      t.string :email,              null: false, default: ""
                                                          ^^
db/migrate/20200310124832_devise_create_authors.rb:8:59: C: Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
      t.string :encrypted_password, null: false, default: ""
                                                          ^^
db/schema.rb:15:16: C: Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
  create_table "articles", force: :cascade do |t|
               ^^^^^^^^^^
db/schema.rb:16:14: C: Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
    t.string "title"
             ^^^^^^^
```

It is complaining that we are using double quotes when we could easily use single quotes. This is an example of a problem youc an automatically  fix. Try running `rubocop --auto-correct`. Notice these lines now have `[Corrected]` in them:

```shell
Offenses:

db/migrate/20200310124832_devise_create_authors.rb:7:59: C: [Corrected] Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
      t.string :email,              null: false, default: ""
                                                          ^^
db/migrate/20200310124832_devise_create_authors.rb:8:59: C: [Corrected] Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
      t.string :encrypted_password, null: false, default: ""
                                                          ^^
db/schema.rb:15:16: C: [Corrected] Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
  create_table "articles", force: :cascade do |t|
               ^^^^^^^^^^
db/schema.rb:16:14: C: [Corrected] Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
    t.string "title"
             ^^^^^^^
```

If you want to see the changes it made, you can check the diff:

```shell
$ git diff db/migrate/20200310124832_devise_create_authors.rb
diff --git a/db/migrate/20200310124832_devise_create_authors.rb b/db/migrate/20200310124832_devise_create_authors.rb
index 50c5341..3232850 100644
--- a/db/migrate/20200310124832_devise_create_authors.rb
+++ b/db/migrate/20200310124832_devise_create_authors.rb
@@ -4,8 +4,8 @@ class DeviseCreateAuthors < ActiveRecord::Migration[6.0]
   def change
     create_table :authors do |t|
       ## Database authenticatable
-      t.string :email,              null: false, default: ""
-      t.string :encrypted_password, null: false, default: ""
+      t.string :email,              null: false, default: ''
+      t.string :encrypted_password, null: false, default: ''

       ## Recoverable
       t.string   :reset_password_token
```
